### ISSUE TITLE
Not working in qemu?

### ISSUE THREAD

**Issue by lrustand** [wulf7/utouch#1]
Hello, I appreciate the work you have done providing this driver. However I can't seem to get it working in FreeBSD. I am running Ubuntu 20.04 on the host with qemu 4.2.0, and FreeBSD 12.1 as guest. The driver compiles and installs fine, and the module is loaded on boot when I set the option `utouch_load="YES"` in /boot/loader.conf as per your instructions, but unfortunately the USB tablet does not work. It is recognized by FreeBSD on boot as seen in dmesg, but it doesn't register any mouseclicks or mouse position.
```
ugen3.2: <QEMU QEMU USB Tablet> at usbus3
utouch0 on uhub3
utouch0: <QEMU QEMU USB Tablet, class 0/0, rev 2.00/0.00, addr2> on usbus3
utouch0: 3 buttons and [XYZ] axes
```

**Comment by wulf7** [comment]
Hi.
utouch kernel module sends events to userland via evdev protocol. Autoconfiguration of such a devices is not supported by Xorg-server 1.18 supplied with 12.1-RELEASE media.
There are 2 options to make it working:
1. Upgrade xorg-server to 1.20 which includes support for autoconfiguration of evdev devices out-of-box. Just upgrade your installed software to current versions with pkg or portupgrade or something else.
2. Manually configure evdev devices in Xorg-server config. See e.g. https://tips.graphica.com.au/freebsd-gnome-on-qemu/ for tips.

**Comment by lrustand** [comment]
Thanks for the quick reply. I will try updating xorg and get back to you.

**Comment by lrustand** [comment]
I tried both your suggestions. First I tried the manual configuration without any luck, then I installed FreeBSD 13 Current with xorg-server 1.20.7, but that didn't work either. Still the same result as before. Module is loaded and device recognised, but it is not responding to the mouse. It is not registering mouse movements or mouseclicks.
I tried checking with xev, but it does not report any mouse click.

**Comment by lrustand** [comment]
Okay, I finally got it working now! It turns out I needed to do both options at the same time in order for it to work. I actually needed to both have xorg-server 1.20 AND manually configure evdev devices. Anyway, thank you so much for the help.
